-- Migration: 001_create_user_info
-- Description: Create user_info table for authentication
-- Note: user_id is generated by the backend, not the database.

CREATE TABLE IF NOT EXISTS user_info (
    user_id       UUID          PRIMARY KEY,
    username      VARCHAR(100)  NOT NULL,
    hash_email    VARCHAR       NOT NULL,
    enc_email     VARCHAR       NOT NULL,
    hash_password VARCHAR       NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_info_username   UNIQUE (username),
    CONSTRAINT uq_user_info_hash_email UNIQUE (hash_email)
);

CREATE INDEX IF NOT EXISTS idx_user_info_username   ON user_info (username);
CREATE INDEX IF NOT EXISTS idx_user_info_hash_email ON user_info (hash_email);
